In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import os
%matplotlib inline

# data = pd.read_csv("C:/Users/yms75/Documents/project/2018___.csv",encoding="cp949")
# data

In [19]:
# dt_condo = data.loc[:,['기준년월','중분류','지출액']] [data.중분류=='콘도']
# dt_hotel = data.loc[:,['기준년월','중분류','지출액']] [data.중분류=='호텔']
# dt_condo_time=dt_condo['기준년월'].values.tolist()
# dt_hotel_money = dt['지출액'].values.tolist()

In [ ]:
# plt.plot(dt_condo['기준년월'],dt_condo['지출액'],'ys-')
# plt.plot(dt_hotel['기준년월'],dt_hotel['지출액'],'gs-')
# plt.title ('Spend money to condo per month')
# plt.xlabel('Time')
# plt.ylabel('Spend_Money')
# plt.ylim(0,20000000)
# plt.xlim(201801,201812)
# plt.xticks(dt_time)
# plt.show()

In [41]:
class DataExtract :
    def __init__ (self,data):
        if '강원' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_강원도", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '경기' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_경기도", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '경남' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_경상남도", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '경북' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_경상북도", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '광주' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_광주광역시", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '대구' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_대구광역시", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '대전' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_대전광역시", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '부산' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_부산광역시", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '서울' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_서울특별시", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '세종' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_세종특별자치시", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '울산' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_울산광역시", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '인천' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_인천광역시", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '전국' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_전국", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '전남' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_전라남도", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '전북' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_전라북도", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '제주' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_제주특별자치도", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '충남' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_충청남도", data)
            dir_csv = dir_csv.replace('\\','/')
        elif '충북' in data:
            dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_충청북도", data)
            dir_csv = dir_csv.replace('\\','/')
        
        self.data = pd.read_csv(dir_csv,encoding="cp949")
#         self.cla = list(set(self.data['중분류'].tolist()))
#         self.timelst = list(set(self.data['기준년월'].tolist()))

In [43]:
df = DataExtract("2020_세종_관광소비 추이.csv")
df.data

       기준년월    광역지자체     중분류        지출액    전년도 지출액
0    202001  세종특별자치시     총소비  6926487.0  7003347.0
1    202001  세종특별자치시  캠핑장/펜션        0.0      100.0
2    202001  세종특별자치시    기타숙박    95301.0   125271.0
3    202001  세종특별자치시     여행업        0.0     4338.0
4    202001  세종특별자치시    육상운송      577.0        0.0
..      ...      ...     ...        ...        ...
160  202012  세종특별자치시  관광유원시설     1460.0    10878.0
161  202012  세종특별자치시     골프장   535578.0   357481.0
162  202012  세종특별자치시    기타레저    20727.0   163188.0
163  202012  세종특별자치시   문화서비스    39146.0   150675.0
164  202012  세종특별자치시     식음료  3882277.0  5916511.0

[165 rows x 5 columns]

In [32]:
data = "2019_강원_관광소비 추이.csv"
dir_csv = os.path.join('C:/Users/yms75/Documents/project', data[:4], data[:4]+"_강원도", data)
dir_csv.replace('\\','/')
data = pd.read_csv(dir_csv,encoding="cp949")
data_mid = data['중분류'].tolist()
lst = list(set(data_mid))

a = data.loc[:,['기준년월','중분류','지출액']] [data.중분류==lst[2]]
a

       기준년월     중분류       지출액
3    201801  캠핑장/펜션   60263.0
23   201802  캠핑장/펜션   64268.0
43   201803  캠핑장/펜션   52651.0
63   201804  캠핑장/펜션   55201.0
83   201805  캠핑장/펜션   83960.0
103  201806  캠핑장/펜션   80998.0
123  201807  캠핑장/펜션  121609.0
143  201808  캠핑장/펜션  185295.0
163  201809  캠핑장/펜션   71401.0
183  201810  캠핑장/펜션   73165.0
203  201811  캠핑장/펜션   51735.0
223  201812  캠핑장/펜션   70886.0

In [ ]:
C:\Users\yms75\Documents\project\2018\2018_강원도\2018_강원_관광소비 추이.csv